import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Header from "@/CustomComponent/Header";
import Sidebar from "@/CustomComponent/SideBar";
import ReduxProvider from "@/Redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ReduxProvider>
      <div className="flex flex-col md:flex-row min-h-screen">
          <Sidebar />
          <div className="flex-1 flex flex-col ">
            <Header />
            <main className="flex-1 p-4">{children}</main>
          </div>
        </div>
        <ToastContainer />
      </ReduxProvider>
        
      </body>
    </html>
  );
}
